"""Writes wood-1.css, wood-2.css and wood-3.css: three wood finishes laid over
the live page (index.html and view.html load them into an iframe of it).

The grain is SVG noise, not images. Each texture is a greyscale-with-alpha
overlay - dark streaks, light streaks, or growth rings (a noise field run
through a zig-zag transfer table, so its contours come out as rings) - laid
over a CSS gradient, so one texture can finish any colour of wood.

    python3 generate.py
"""
from urllib.parse import quote

def svg(filter_body, w, h):
    s = (f"<svg xmlns='http://www.w3.org/2000/svg' width='{w}' height='{h}'>"
         f"<filter id='f' x='0' y='0' width='100%' height='100%' color-interpolation-filters='sRGB'>{filter_body}</filter>"
         f"<rect width='100%' height='100%' filter='url(#f)'/></svg>")
    return 'url("data:image/svg+xml,' + quote(s, safe="/:=' ") + '")'

def ink(k, b, light=False):
    """Colour matrix: alpha from the noise's red channel, colour black or warm light."""
    rgb = "0 0 0 0 1 0 0 0 0 .88 0 0 0 0 .7" if light else "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0"
    return f"<feColorMatrix values='{rgb} {k} 0 0 0 {b}'/>"

def streaks(fx, fy, k, b, seed, light=False, w=900, h=450, oct=2):
    return svg(f"<feTurbulence type='fractalNoise' baseFrequency='{fx} {fy}' numOctaves='{oct}' seed='{seed}' stitchTiles='stitch'/>"
               + ink(k, b, light), w, h)

def rings(fx, fy, k, seed, bands=8, light=False, w=900, h=450):
    table = " ".join(["0 1"] * bands) + " 0"
    return svg(f"<feTurbulence type='fractalNoise' baseFrequency='{fx} {fy}' numOctaves='2' seed='{seed}' stitchTiles='stitch'/>"
               f"<feComponentTransfer><feFuncR type='table' tableValues='{table}'/></feComponentTransfer>"
               + ink(k, 0, light), w, h)

HEAD = """/* {title}
   Generated by generate.py - edit that, not this file. */
"""

def theme(n, title, desc, t):
    """t: dict of textures and colours for one finish."""
    grain = f"{t['grain']}, {t['rings']}, {t['pores']}"
    size3 = ", ".join([t['size']] * 3)             # one size per layer of `grain`
    css = HEAD.format(title=f"{n} · {title} — {desc}") + f"""
:root {{
  --wood-hi: {t['hi']}; --wood: {t['mid']}; --wood-lo: {t['lo']}; --wood-dark: {t['dark']};
}}

/* ---- The bookshelf ---- */
.shelf-wall {{
  background:
    linear-gradient(180deg,
      rgba(255, 228, 184, 0.16) 0, rgba(0, 0, 0, 0) 20px, rgba(0, 0, 0, 0.42) var(--rail),
      rgba(0, 0, 0, 0.22) calc(var(--rail) + 1px), rgba(0, 0, 0, 0.22) calc(100% - var(--rail) - 1px),
      rgba(0, 0, 0, 0.42) calc(100% - var(--rail)), rgba(0, 0, 0, 0) calc(100% - 20px), rgba(255, 228, 184, 0.14) 100%),
    {grain},
    linear-gradient(180deg, {t['wall1']}, {t['wall2']});
  background-size: 100% 100%, {size3}, 100% 100%;
}}
.bay {{
  background:
    linear-gradient(180deg, rgba(255, 228, 184, 0.14), rgba(0, 0, 0, 0) 40%, rgba(0, 0, 0, 0.28)),
    {grain},
    linear-gradient(180deg, {t['hi']}, {t['lo']});
  background-size: 100% 100%, {size3}, 100% 100%;
  {t.get('bay_extra', '')}
}}
.bay__well {{
  background:
    radial-gradient(60% 70% at 50% 0%, rgba(255, 222, 150, 0.2), transparent 70%),
    linear-gradient(180deg, rgba(0, 0, 0, 0.45), rgba(0, 0, 0, 0.2) 30%, rgba(0, 0, 0, 0.55)),
    {t['vgrain']},
    linear-gradient(90deg, {t['back1']}, {t['back2']} 50%, {t['back1']});
  background-size: 100% 100%, 100% 100%, {t['vsize']}, 100% 100%;
}}
.bay__plank,
.ledge {{
  background:
    linear-gradient(180deg, rgba(255, 232, 196, 0.3), rgba(0, 0, 0, 0) 35%, rgba(0, 0, 0, 0.45)),
    {t['grain']},
    {t['plank']};
  background-size: 100% 100%, {t['size']}, 100% 100%;
}}
.ledge::after {{
  background:
    radial-gradient(circle at 11px 5px, #f0d69a 0 1.5px, #c9a961 2.5px, transparent 3px),
    linear-gradient(180deg, rgba(255, 235, 200, 0.12), rgba(0, 0, 0, 0.45)),
    {t['grain']},
    {t['mid']};
}}

/* ---- The brown panels: Details, the teachers band, the featured article ---- */
.card--choc,
.article-feature {{
  background:
    linear-gradient(165deg, rgba(255, 232, 196, {t['sheen']}), rgba(255, 232, 196, 0) 38%, rgba(0, 0, 0, 0) 60%, rgba(0, 0, 0, 0.22)),
    {grain},
    linear-gradient(160deg, {t['panel1']}, {t['panel2']});
  background-size: 100% 100%, {size3}, 100% 100%;
  border-color: {t['edge']};
  box-shadow: {t['panel_shadow']};
}}
.card--choc:hover {{ border-color: {t['edge_hover']}; }}
.teachers-band {{
  background:
    radial-gradient(900px 420px at 50% 0%, rgba(255, 232, 190, {t['glow']}), transparent 70%),
    {t.get('band_boards', 'linear-gradient(transparent, transparent)')},
    {grain},
    linear-gradient(180deg, {t['panel1']}, {t['panel2']});
  background-size: 100% 100%, 100% 100%, {size3}, 100% 100%;
}}

/* ---- Small brown pieces ---- */
.aud-toggle__track {{
  background:
    linear-gradient(180deg, rgba(255, 232, 196, 0.22), rgba(0, 0, 0, 0.25)),
    {t['grain']},
    {t['track']};
  background-size: 100% 100%, 300px 150px, 100% 100%;
}}
.video-card__thumb--pattern {{
  background-image:
    url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='64' height='64'%3E%3Cg fill='none' stroke='%23eec25a' stroke-opacity='.3'%3E%3Crect x='17' y='17' width='30' height='30'/%3E%3Crect x='17' y='17' width='30' height='30' transform='rotate(45 32 32)'/%3E%3Ccircle cx='32' cy='32' r='5'/%3E%3C/g%3E%3C/svg%3E"),
    linear-gradient(160deg, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.35)),
    {grain},
    linear-gradient(160deg, {t['panel1']}, {t['panel2']});
  background-size: 64px 64px, 100% 100%, {size3}, 100% 100%;
}}
{t.get('extra', '')}"""
    open(f"wood-{n}.css", "w").write(css)

# 1 · Walnut: dark, straight, quiet grain. Closest to today's chocolate.
theme(1, "Walnut", "dark straight-grained walnut, oiled not lacquered; the quietest.", dict(
    grain=streaks(0.0012, 0.22, 1.3, -0.5, 3),
    rings=rings(0.0014, 0.018, 0.2, 11, bands=11),
    pores=streaks(0.004, 0.8, 1.0, -0.5, 5, oct=1),
    vgrain=streaks(0.22, 0.0012, 1.3, -0.5, 8, w=450, h=900),
    size="900px 450px", vsize="450px 900px",
    hi="#5a3a20", mid="#462c16", lo="#34200f", dark="#1e1208",
    wall1="#3a2412", wall2="#24160a",
    back1="#1e1208", back2="#2c1b0d",
    plank="linear-gradient(180deg, #6e4a2a, #3a2412)",
    panel1="#5a3418", panel2="#34190a",
    sheen=0.07, glow=0.1,
    edge="rgba(189, 93, 15, 0.6)", edge_hover="#bd5d0f",
    panel_shadow="inset 0 1px 0 rgba(255, 232, 196, 0.16), 0 30px 60px -30px rgba(70, 34, 6, 0.6)",
    track="linear-gradient(160deg, #6e4a2a, #3a2412)",
))

# 2 · Mahogany: red-brown figured wood under a lacquer, with a gold inlay line.
theme(2, "Mahogany & Inlay", "red-brown figured mahogany under a lacquer sheen, the panels inlaid with a gold line; the richest.", dict(
    grain=streaks(0.0012, 0.16, 1.2, -0.46, 21),
    rings=rings(0.002, 0.011, 0.2, 4, bands=12, light=True),
    pores=streaks(0.004, 0.7, 0.9, -0.45, 9, oct=1),
    vgrain=streaks(0.16, 0.0012, 1.2, -0.46, 14, w=450, h=900),
    size="900px 450px", vsize="450px 900px",
    hi="#7a3a1a", mid="#5e2c12", lo="#44200c", dark="#261006",
    wall1="#50220d", wall2="#2e1307",
    back1="#220d04", back2="#34160a",
    plank="linear-gradient(180deg, #8c4520, #4a200c)",
    panel1="#7a3412", panel2="#3e1807",
    sheen=0.16, glow=0.14,
    edge="rgba(227, 179, 74, 0.5)", edge_hover="rgba(238, 194, 90, 0.85)",
    panel_shadow="inset 0 1px 0 rgba(255, 232, 196, 0.2), 0 30px 60px -30px rgba(70, 20, 6, 0.6)",
    track="linear-gradient(160deg, #8c4520, #4a200c)",
    extra="""/* The inlay: a gold line inside each panel, and a gold string along the band's rails */
.teachers-band::before, .teachers-band::after { border-color: rgba(238, 194, 90, 0.75); }
.card--choc, .article-feature { outline: 1px solid rgba(227, 179, 74, 0.55); outline-offset: -10px; }
.bay__well { outline: 1px solid rgba(227, 179, 74, 0.3); outline-offset: 3px; }
""",
))

# 3 · Oak boards: lighter oak laid in planks, with raised-and-fielded panels.
theme(3, "Oak Boards & Panels", "warm oak with open rings, the bands laid as planks and the cards as framed, raised panels; the most handmade.", dict(
    grain=streaks(0.0012, 0.24, 1.1, -0.44, 31),
    rings=rings(0.0024, 0.026, 0.4, 17, bands=13),
    pores=streaks(0.005, 1.0, 1.1, -0.56, 2, oct=1),
    vgrain=streaks(0.24, 0.0012, 1.2, -0.46, 6, w=450, h=900),
    size="900px 450px", vsize="450px 900px",
    hi="#9a6834", mid="#7c5026", lo="#5e3a18", dark="#3a220c",
    wall1="#7a4e24", wall2="#553214",
    back1="#2a1809", back2="#3c2410",
    plank="linear-gradient(180deg, #a0703c, #5e3a18)",
    panel1="#83542a", panel2="#57330f",
    sheen=0.1, glow=0.1,
    edge="rgba(20, 8, 0, 0.5)", edge_hover="rgba(189, 93, 15, 0.8)",
    panel_shadow="inset 0 0 0 1px rgba(255, 228, 184, 0.14), inset 0 0 0 14px rgba(0, 0, 0, 0.16), inset 0 0 0 15px rgba(255, 228, 184, 0.16), inset 0 0 0 16px rgba(0, 0, 0, 0.3), 0 30px 60px -30px rgba(60, 30, 6, 0.6)",
    track="linear-gradient(160deg, #a0703c, #5e3a18)",
    band_boards="repeating-linear-gradient(180deg, rgba(0, 0, 0, 0) 0 117px, rgba(0, 0, 0, 0.5) 117px 119px, rgba(255, 228, 184, 0.18) 119px 120px)",
    bay_extra="",
    extra="""/* Planks on the wall too, and gold titles a shade lighter on the lighter wood */
.shelf-wall::before, .shelf-wall::after { background-color: rgba(0, 0, 0, 0.12); }
.shelf-wall > .wrap { position: relative; }
.tgroup__label, .tier__amount, .article-feature .article__title, .teachers-band .section__heading { color: #f6d27a; }
.card__kicker, .tgroup__years, .kicker--on-choc, .article-feature .article__meta { color: #f2c860; }
.row, .tier__label, .article-feature .article__excerpt { text-shadow: 0 1px 2px rgba(0, 0, 0, 0.45); }
""",
))
